#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#=========================

if [ $# -eq 0 ]
  then
    echo "Please enter the number of processors."
    exit 1
fi
procs=$1 #first argument is the number of processors to use
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Remove log files
rm log.*
rm -r pro*

# Get application name
application=`getApplication`

cp -r zeroOrig 0
# create the mesh
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel snappyHexMesh $procs -overwrite
runApplication reconstructParMesh -constant
rm -r pro*
rm -r 0
#runApplication $application
#runParallel `getApplication` $procs
#
#runApplication reconstructParMesh -constant
#mpirun -np $procs redistributePar -reconstruct -parallel 
##runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
