#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#=========================
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Get application name
application=`getApplication`
rm log.*
cp -r zeroOrig 0
# create the mesh
runApplication decomposePar




# ----------------------------------------------------------------- end-of-file
